#!/bin/sh

set -e

case "$DPKG_MAINTSCRIPT_PACKAGE" in
linux-headers-droid4|linux-image-droid4-dbg)
	exit 0
	;;
esac

VERSION="$(dpkg -s "$DPKG_MAINTSCRIPT_PACKAGE" | sed -n 's/^Version: //p')"
VERSION="$(printf "%s" "$version" | cut -d'-' -f 1)"

rm -f /boot/zImage /boot/boot
ln -s /boot/vmlinuz-"$VERSION" /boot/zImage
ln -s /usr/lib/linux-image-droid4/omap4-droid4-xt894.dtb /boot/omap4-droid4-xt894.dtb
ln -s /boot /boot/boot
